# Generated by Django 6.0.2 on 2026-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
