# Generated by Django 6.0.2 on 2026-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_remove_vacancy_vacancies_v_publish_848807_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='skills',
            new_name='skills_raw',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='vacancies', to='vacancies.skill', verbose_name='Навыки'),
        ),
    ]
