# Generated by Django 6.0.2 on 2026-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='region_code',
            field=models.CharField(max_length=3, null=True, verbose_name='Код региона'),
        ),
    ]
