# Generated by Django 6.0.2 on 2026-03-24 05:42

from django.db import migrations


def normalize_skill(skill: str) -> str:
    return skill.strip().lower()


def forwards(apps, schema_editor):
    Vacancy = apps.get_model('vacancies', 'Vacancy')
    Skill = apps.get_model('vacancies', 'Skill')

    db_alias = schema_editor.connection.alias

    skills_cache = {}

    for vacancy in Vacancy.objects.using(db_alias).all().iterator():
        raw = getattr(vacancy, 'skills_raw', None)

        if not raw:
            continue

        raw_skills = raw.split(',')

        skill_objs = []

        for raw_skill in raw_skills:
            name = normalize_skill(raw_skill)

            if not name:
                continue

            if name not in skills_cache:
                skill_obj, _ = Skill.objects.using(db_alias).get_or_create(name=name)
                skills_cache[name] = skill_obj

            skill_objs.append(skills_cache[name])

        vacancy.skills.add(*skill_objs)


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_skill_vacancy_skills_raw_remove_vacancy_skills_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]