# Generated by Django 6.0.2 on 2026-05-26 18:09

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_region'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vacancy',
            managers=[
                ('regions', django.db.models.manager.Manager()),
            ],
        ),
    ]
