# Generated by Django 6.0.2 on 2026-03-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20260324_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='skills_raw',
        ),
    ]
